name: Build

on:
  push:
  pull_request:

jobs:
  verify:
    name: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3.3.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Verify with Maven
        run: mvn --batch-mode --update-snapshots verify
